services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vrooom_db
      POSTGRES_USER: vrooom_user
      POSTGRES_PASSWORD: haslo123
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
